### ISSUE TITLE
Rigel under RaveOS mining IRONFISH to Nicehash, miner doesn't report worker name

### ISSUE THREAD

**Issue by ikorzha** [rigelminer/rigel#129]
Rigel miner under RaveOS mining IRONFISH to Nicehash, miner doesn't report worker name even if manually specified via --worker in miner CLI:

I have 3 workers mining with Rigel IRONFISH to NIcehash and in NIcehash all 3 workers total output are reported as "__DEFAULT__" there are no breakdown per worker, eventhough workers are properly named.
Please see screenshot:

![image](https://github.com/rigelminer/rigel/assets/11211789/a72898b1-c19f-4bd7-a8af-afb77449f655)

Rig name is absent:
![image](https://github.com/rigelminer/rigel/assets/11211789/e346a99d-e450-4bde-9d36-a6a6fae7a3ce)

**Comment by rigelminer** [comment]
When I mine ironfish to other pools, e.g. herominers, the worker name is correctly identified and displayed. I'm thinking this could be a Nicehash issue. Have you tried using other miners?

**Comment by ikorzha** [comment]
Absolutely with other miners rig name is properly reported. Example below: I have moved RIG5 to LOLminer and now it is reporting name properly.
Please see below:

![image](https://github.com/rigelminer/rigel/assets/11211789/e209340d-ef1a-4bb3-ae48-9b10bd7d3a88)

**Comment by rigelminer** [comment]
Thank you. I did some investigation and it appears to be an issue on Nicehash side.
In the early days, when it was discovered ironfish hashrate can be x3 of what it was supposed to be, the TRM team has published stratum v2 specification https://github.com/Kerney666/ironfish/blob/trm_stratum/TRM_STRATUM.md according to which the worker name should be passed in `mining.subscribe` message in `name` field, see example:
```
{"id":1,"method":"mining.subscribe","body":{"version":2,"agent":"teamredminer/0.10.9","publicAddress":"3005e5b38199c0549029dc5cc1991cb285f8de34cd4324caf9239d24c7c7af3b","name":"mytestrig"}}
```
However, Nicehash expects the worker name to be part of the public address, e.g. `3005e5b38199c0549029dc5cc1991cb285f8de34cd4324caf9239d24c7c7af3b.mytestrig`. You can contact their support and refer to this ticket, and change your wallet address format to "WALLET.WORKER" in the meantime.
I'm fairly certain you are not experiencing this issue with lolminer because RaveOS concatenates your wallet address and the worker name under the hood before passing it to the miner.

I'm going to close this issue as I don't think it's something I need to fix, but feel free to continue the discussion.

**Comment by ikorzha** [comment]
Workaround to adding .RIG to wallet works. Thanks for a workaround info.
