### ISSUE TITLE
Can you tell me how to set up a proxy to bypass possible mining detection?

### ISSUE THREAD

**Issue by njursi** [rigelminer/rigel#175]
Thank you so much！

**Comment by rigelminer** [comment]
Using `--dns-over-https` along with SSL (`stratum+ssl://...` instead of `stratum+tcp://...`) is usually enough. In difficult cases you may need to configure the miner to use a socks5 proxy with `--proxy YOUR_SOCKS5_PROXY`. That's assuming you have one. If not, you can search for free ones or set it up yourself - there are plenty of guides on the internet, but you will need to rent a server.

**Comment by njursi** [comment]
ok, thankss, you mean the first type of general setting is enough to avoid censorship, right?

**Comment by rigelminer** [comment]
Depending on how sophisticated the mining detection system is, it may be enough, yes.
