### ISSUE TITLE
Dev fee connect error and mining stopped

### ISSUE THREAD

**Issue by albamef** [rigelminer/rigel#176]
![image](https://github.com/rigelminer/rigel/assets/74110396/a288eb95-79b1-444e-8bdb-9a27f8e7cc6a)

Why mining stopped???

**Comment by albamef** [comment]
My farms keep rebooting due to this error. How to remove it?

**Comment by MoMMoNdev** [comment]
I have the same. Cyclic restart constantly.

**Comment by Mihaxxi** [comment]
i have same error "[2024-04-15 15:17:18] Dev fee connectivity error: all pools are unavailable". 
"[2024-04-15 15:17:22] all devices stopped
[2024-04-15 15:17:22] all miner tasks finished
[2024-04-15 15:17:22] miner terminated"

On my 2 different locations with 2 different providers. :(
Why???

Can you pls fix it on next release? Not need to stop mining if any problem with "Dev fee connectivity".

**Comment by rigelminer** [comment]
I apologise to everyone who experienced downtime earlier today running Rigel due to the "Dev fee connectivity" error. The issue was caused by one of the dev fee servers going over the limit of the number of open connections which made its traffic instantaneously failover to other servers causing a chain reaction with mining clients reconnecting over and over again only to increase the load further. I increased the connection limit, upgraded the servers to more CPU/RAM, and checked that a single server can now handle a burst of traffic. Please let me know if you're still facing this issue. Everything looks normal from my side. Thank you for your patience.
